routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::group(['middleware' => ['auth', 'permission']], function () {
    

    Route::resource('tags', 'TagController', [
        'except' => ['show']
    ]);

    Route::resource('suppliers', 'SupplierController');

    Route::resource('customers', 'CustomerController');

    // Route::resource('addresses', 'AddressController');

    Route::resource('products', 'ProductController');
   
	Route::resource('inventories', 'InventoryController');

	Route::resource('categories', 'CategoryController');

	Route::resource('orders', 'OrderController');

	Route::resource('payments', 'PaymentController', [
        'only' => ['index', 'create', 'destroy', 'store']
    ]);

	Route::get('dashboard', 'HomeController@index')->name('dashboard');

    Route::resource('stock-adjustments', 'StockAdjustmentController', [
        'only' => ['index', 'create', 'store']
    ]);

    Route::resource('users', 'UserController');

    Route::get('profile', 'ProfileController@index')->name('profile.show');
    Route::post('profile', 'ProfileController@store')->name('profile.update');

    Route::redirect('/', '/dashboard', 301);

    Route::resource('roles', 'RoleController', [
        'except' => ['show']
    ]);
});

app/Models/Inventory.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Inventory
 * @package App\Models
 * @version September 6, 2017, 6:32 am UTC
 *
 * @property integer supplier_id
 * @property timestamp supplied_at
 */
class Inventory extends Model
{
    use SoftDeletes;

    public $table = 'inventories';

    protected $dates = ['deleted_at', 'supplied_at'];

    public $fillable = [
        'supplier_id',
        'supplied_at',
        'total_amount',
        'paid_amount',
        'due_amount',
        'notes',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'supplier_id' => 'integer',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'supplier_id' => 'required|exists:suppliers,id',
        'supplied_at' => 'date',
        'products' => 'required|array',
    ];

    public function supplier()
    {
        return $this->belongsTo(Supplier::class);
    }

    public function products()
    {
        return $this->belongsToMany(Product::class, 'inventory_products')
            ->withPivot('quantity','price_per_unit', 'total_amount', 'sold_quantity');
    }

    public function setSuppliedAtAttribute($value)
    {
        $this->attributes['supplied_at'] = Carbon::parse($value);
    }
}

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\InventoryDataTable;
use App\Http\Controllers\AppBaseController;
use App\Http\Requests\CreateInventoryRequest;
use App\Http\Requests\UpdateInventoryRequest;
use App\Repositories\InventoryRepository;
use App\Repositories\SupplierRepository;
use Flash;
use Illuminate\Http\Request;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class InventoryController extends AppBaseController
{
    /** @var  InventoryRepository */
    private $inventoryRepository;
    private $supplierRepository;

    public function __construct(InventoryRepository $inventoryRepo, SupplierRepository $supplierRepo)
    {
        $this->inventoryRepository = $inventoryRepo;
        $this->supplierRepository = $supplierRepo;
    }

    /**
     * Display a listing of the Inventory.
     *
     * @param Request $request
     * @return Response
     */
    public function index(InventoryDataTable $inventoryDataTable)
    {
        // $this->inventoryRepository->pushCriteria(new RequestCriteria($request));
        // $inventories = $this->inventoryRepository->all();

        // return view('inventories.index')
        //     ->with('inventories', $inventories);
        
        return $inventoryDataTable->render('inventories.index');
    }

    /**
     * Show the form for creating a new Inventory.
     *
     * @return Response
     */
    public function create()
    {
        $suppliers = $this->supplierRepository->all();
        return view('inventories.create', compact('suppliers'));
    }

    /**
     * Store a newly created Inventory in storage.
     *
     * @param CreateInventoryRequest $request
     *
     * @return Response
     */
    public function store(CreateInventoryRequest $request)
    {
        $input = $request->all();

        $inventory = $this->inventoryRepository->create($input);

        Flash::success('Inventory saved successfully.');

        return redirect(route('inventories.index'));
    }

    /**
     * Display the specified Inventory.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $inventory = $this->inventoryRepository->findWithoutFail($id);

        if (empty($inventory)) {
            Flash::error('Inventory not found');

            return redirect(route('inventories.index'));
        }

        return view('inventories.show')->with('inventory', $inventory);
    }

    /**
     * Show the form for editing the specified Inventory.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $inventory = $this->inventoryRepository
            ->with(['products.category'])
            ->findWithoutFail($id);

        if (empty($inventory)) {
            Flash::error('Inventory not found');

            return redirect(route('inventories.index'));
        }

        $suppliers = $this->supplierRepository->all();
        return view('inventories.edit', compact('suppliers', 'inventory'));
    }

    /**
     * Update the specified Inventory in storage.
     *
     * @param  int              $id
     * @param UpdateInventoryRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateInventoryRequest $request)
    {
        $inventory = $this->inventoryRepository->findWithoutFail($id);

        if (empty($inventory)) {
            Flash::error('Inventory not found');

            return redirect(route('inventories.index'));
        }

        $inventory = $this->inventoryRepository->update($request->all(), $id);

        Flash::success('Inventory updated successfully.');

        return redirect(route('inventories.index'));
    }

    /**
     * Remove the specified Inventory from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $inventory = $this->inventoryRepository->findWithoutFail($id);

        if (empty($inventory)) {
            Flash::error('Inventory not found');

            return redirect(route('inventories.index'));
        }

        $this->inventoryRepository->delete($id);

        Flash::success('Inventory deleted successfully.');

        return redirect(route('inventories.index'));
    }
}

resources/views/inventories/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Inventory
        </h1>
    </section>
    <div class="content">
        @include('flash::message')
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    @yield('form.open')
                    {!! Form::open(['route' => 'inventories.store']) !!}

                        @include('inventories.fields')

                    {!! Form::close() !!}
                    @yield('form.close')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/inventories/datatables_actions.blade.php
{!! Form::open(['route' => ['inventories.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('inventories.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('inventories.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/inventories/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Inventory
        </h1>
   </section>
   <div class="content">
       @include('flash::message')
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                    @yield('form.open')
                   {!! Form::model($inventory, ['route' => ['inventories.update', $inventory->id], 'method' => 'patch']) !!}

                        @include('inventories.fields')

                   {!! Form::close() !!}
                   @yield('form.close')
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/inventories/fields.blade.php
<!-- Supplier Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('supplier_id', 'Supplier') !!}
	<select name="supplier_id" id="supplier_id" required class="form-control" data-placeholder="-- Select --"
		style="width: 100%">
		<option></option>
		@foreach($suppliers as $supplier)
			@if(isset($inventory) && $inventory->supplier_id == $supplier->id)
				<option selected value="{{ $supplier->id }}">{{ $supplier->name }}</option>
			@else
				<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>
			@endif
		@endforeach
	</select>
</div>

<div class="form-group col-sm-6">
    {!! Form::label('supplied_at', 'Date') !!}
	{!! Form::datetimeLocal('supplied_at', date('Y-m-d\TH:i'), ['class' => 'form-control', 'required']) !!}
</div>

<div class="col-sm-12 form-group">
	<label style="margin-bottom: 10px;display: block;">
		Product Line
		<button type="button" class="btn btn-primary btn-sm pull-right"
			data-toggle="modal"
			data-target="#product-list-modal">
			<i class="fa fa-plus"></i>
			Add Product
		</button>
	</label>
	<div class="box box-default">
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<td>Product</td>
					<td>Category</td>
					<td>Price Per Unit</td>
					<td>Quantity</td>
					<td>Amount</td>
				</tr>
			</thead>
			<tbody>
				<tr v-if="!product_line.length">
					<td colspan="5" align="center">No Product Line</td>
				</tr>
				<tr v-for="(line,index) in product_line">
					<th v-text="line.product.name">
					</th>
					<th v-text="line.product.category.name"></th>
					<td>
						<input type="number" class="form-control" step="0.10" v-model="line.price_per_unit"
							:name="'products[' + line.product.id + '][price_per_unit]'"
							min="0">
						<input type="hidden" :name="'products[' + line.product.id + '][product_id]'" v-model="line.product.id">
						<input type="hidden" :name="'products[' + line.product.id + '][sold_quantity]'" v-model="line.sold_quantity">
					</td>
					<td>
						<input type="number" class="form-control" v-model="line.quantity"
							:name="'products[' + line.product.id + '][quantity]'"
							:min="line.sold_quantity || 0">
					</td>
					<td>
						<input type="text" readonly class="form-control" v-model="computeProductLineTotalAmount(line)"
							:name="'products[' + line.product.id + '][total_amount]'">
					</td>
					<td>
						<button type="button" class="btn btn-sm btn-danger"
							v-if="!line.sold_quantity"
							@click="removeProductLine(index)">
							<i class="fa fa-times-circle"></i>
						</button>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div class="col-sm-6 form-group">
	<label for="notes">Notes</label>
	{!! Form::textarea('notes', null, ['class' => 'form-control', 'rows' => 5, 'cols' => 30]) !!}
</div>
<div class="col-sm-6 form-horizontal">
	<div class="form-group">
		<label for="total_amount" class="control-label col-sm-4">Total Amount</label>
		<div class="col-sm-8">
			{!! Form::number('total_amount', null, ['class' => 'form-control', 'v-model' => 'inventory.total_amount', 'readonly']) !!}
		</div>
	</div>
	<div class="form-group">
		<label for="paid_amount" class="control-label col-sm-4">Paid Amount</label>
		<div class="col-sm-8">
			{!! Form::number('paid_amount', null, [
				'class' => 'form-control', 'v-model' => 'inventory.paid_amount', 'step' => '0.10',
				':max' => 'inventory.total_amount'
			]) !!}
		</div>
	</div>
	<div class="form-group">
		<label for="due_amount" class="control-label col-sm-4">Due</label>
		<div class="col-sm-8">
			{!! Form::text('due_amount', null, ['class' => 'form-control', 'v-model' => 'inventory.due_amount', 'readonly']) !!}
		</div>
	</div>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('inventories.index') !!}" class="btn btn-default">Cancel</a>
</div>
@section('form.close')
<div class="modal fade" tabindex="-1" role="dialog" id="product-list-modal">
  	<form v-on:submit.prevent="addProductLine()">
  		<div class="modal-dialog" role="document">
  		  	<div class="modal-content">
				<div class="modal-header">
	      			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	      			<h4 class="modal-title">Add Product</h4>
	    		</div>
	    		<div class="modal-body">
		      		<div class="form-group">
		      			<label for="product">Product</label>
		      			{{-- <select required class="form-control" style="width: 100%" data-placeholder="-- Select --">
		      				<option></option>
		      				<option v-for="product in getUnselectedProducts" :value="product.id" v-text="product.name"
		      					:key="product.name"></option>
		      			</select>
		      			 --}}
		      			 <multiselect @select="selectedOption" :options="getUnselectedProducts" label="name" v-model="new_product.product"></multiselect>
		      		</div>
		      		<div class="form-group">
		      			<label for="price_per_unit">Price Per Unit</label>
		      			<input v-model="new_product.price_per_unit" required type="number" step="0.10" class="form-control" id="price_per_unit">
		      		</div>
		      		<div class="form-group">
		      			<label for="quantity">Quantity</label>
		      			<input v-model="new_product.quantity" min="1" required type="number" class="form-control" id="quantity">
		      		</div>
		      		<div class="form-group">
		      			<label for="quantity">Amount</label>
		      			<input v-model="new_product.total_amount" disabled type="number" class="form-control" id="total_amount">
		      		</div>
	    		</div>
	    		<div class="modal-footer">
	      			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      			<button type="submit" class="btn btn-primary">Add</button>
	    		</div>
  		  	</div><!-- /.modal-content -->
		</div>
  	</form>
</div>
@endsection
@section('scripts')
<script>
	new Vue({
		el: '.content',
		data: {
			product_line: {!! isset($inventory) ? $inventory->products->map(function ($p) {
				return [
					'id' => $p->id,
					'product' => $p,
					'total_amount' => $p->pivot->total_amount,
					'quantity' => $p->pivot->quantity,
					'price_per_unit' => $p->pivot->price_per_unit,
					'sold_quantity' => $p->pivot->sold_quantity,
				];
			}): '[]' !!},
			products: [],
			new_product: {
				product: '',
				price_per_unit: '',
				quantity: '',
				total_amount: '',
			},
			inventory: {!! isset($inventory) ? $inventory : '{paid_amount : "", due_amount: 0, total_amount: 0}' !!}
		},
		computed: {
			newProductTotalAmount () {
				return (this.new_product.quantity * this.new_product.price_per_unit).toFixed(2) || ''
			},
			getUnselectedProducts () {
				var products = this.product_line.map(line => line.product.id)

				return this.products.filter(p => {
					return products.indexOf(p.id) < 0
				})
			},
		},
		watch: {
			inventory: {
				handler: function (val, oldVal) {
					this.inventory.due_amount = (val.total_amount - val.paid_amount).toFixed(2)
				},
				deep: true
			},
			product_line: {
				handler: function (val, oldVal) {
					this.inventory.total_amount = this.product_line.reduce((sum, p) => {
						return sum + Number(p.total_amount)
					}, 0).toFixed(2)
					this.inventory.due_amount = (this.inventory.total_amount - this.inventory.paid_amount).toFixed(2)
				},
				deep: true,
			},
			new_product: {
				handler: function (val, oldVal) {
					this.new_product.total_amount = val.price_per_unit * val.quantity
				},
				deep: true
			}
		},
		created () {
			this.getProducts()
		},
		mounted () {
			var self = this

			$("#product-list-modal select").on("change", function () {
				var product = _.find(self.products, { 'id': Number($(this).val())})
				self.new_product.product = product
			})
			$("#product-list-modal").on('hidden.bs.modal', function (e) {
				self.new_product.product = ''
				self.new_product.price_per_unit = ''
				self.new_product.quantity = ''
				self.new_product.total_amount = ''
			})
		},
		methods: {
			getProducts () {
				axios.get('/api/products', {
						params: {
							limit: 1000,
							with: 'category'
						}
					})
					.then((response) => {
					 	this.products = response.data.data.data
					})
			},
			addProductLine() {
				this.product_line.push({
					product: this.new_product.product,
					price_per_unit: this.new_product.price_per_unit,
					quantity: this.new_product.quantity,
					total_amount: this.new_product.total_amount
				})
				$("#product-list-modal").modal('toggle')
			},
			removeProductLine (index) {
				this.product_line.splice(index, 1)
			},
			computeProductLineTotalAmount(line) {
				return line.total_amount = (line.price_per_unit * line.quantity).toFixed(2) || null
			},
            selectedOption (selectedOption, id) {
                this.new_product.price_per_unit = selectedOption.cost_price
            }
		}
	})
</script>
@endsection

resources/views/inventories/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Inventories</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('inventories.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('inventories.table')
            </div>
        </div>
    </div>
@endsection

resources/views/inventories/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Inventory
            <a href="{{ route('inventories.edit', $inventory->id) }}" class="btn btn-primary pull-right">
                <i class="fa fa-pencil"></i>
                Edit
            </a>
        </h1>
    </section>
    <div class="content">
        <div class="row">
            <div class="col-sm-9">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            <div class="form-group col-sm-6">
                                <label for="date">Date</label>
                                <p>{{ $inventory->supplied_at->format("M d, Y H:i A") }}</p>
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="total_amount">Total Amount</label>
                                <p>{{ $inventory->total_amount }}</p>
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="paid_amount">Paid Amount</label>
                                <p>{{ $inventory->paid_amount }}</p>
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="due_amount">Due</label>
                                <p>{{ $inventory->due_amount }}</p>
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="notes">Note</label>
                                <p>{{ $inventory->notes }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <h4>Inventory Items</h4>
                <div class="box box-primary">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <td>Product</td>
                                <td>Category</td>
                                <td>Price Per Unit</td>
                                <td>Quantity</td>
                                <td>Amount</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($inventory->products as $product)
                                <tr>
                                    <td>{{ $product->name }}</td>
                                    <td>{{ optional($product->category)->name }}</td>
                                    <td>{{ $product->pivot->price_per_unit }}</td>
                                    <td>{{ $product->pivot->quantity }}</td>
                                    <td>{{ $product->pivot->total_amount }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">
                            Supplier
                        </h3>
                    </div>
                    <div class="box-body">
                        <dl>
                            <dt>ID</dt>
                            <dd><a href="{{ route('suppliers.show', $inventory->supplier->uid) }}">
                                {{ $inventory->supplier->uid }}
                            </a></dd>
                            <dt>Name</dt>
                            <dd>{{ $inventory->supplier->name }}</dd>
                            <dt>Email</dt>
                            <dd><a href="mailto:{{ $inventory->supplier->email }}">{{ $inventory->supplier->email }}</a></dd>
                            <dt>Phone</dt>
                            <dd><abbr title="Phone">P:</abbr> {{ $inventory->supplier->phone }}</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <a href="{!! route('inventories.index') !!}" class="btn btn-default">
            <i class="fa fa-angle-double-left"></i>
            Back</a>
    </div>
@endsection

resources/views/inventories/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $inventory->id !!}</p>
</div>

<!-- Supplier Id Field -->
<div class="form-group">
    {!! Form::label('supplier_id', 'Supplier Id:') !!}
    <p>{!! $inventory->supplier_id !!}</p>
</div>

<!-- Supplied At Field -->
<div class="form-group">
    {!! Form::label('supplied_at', 'Supplied At:') !!}
    <p>{!! $inventory->supplied_at !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $inventory->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $inventory->updated_at !!}</p>
</div>

resources/views/inventories/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection