routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::group(['middleware' => ['auth', 'permission']], function () {
    

    Route::resource('tags', 'TagController', [
        'except' => ['show']
    ]);

    Route::resource('suppliers', 'SupplierController');

    Route::resource('customers', 'CustomerController');

    // Route::resource('addresses', 'AddressController');

    Route::resource('products', 'ProductController');
   
	Route::resource('inventories', 'InventoryController');

	Route::resource('categories', 'CategoryController');

	Route::resource('orders', 'OrderController');

	Route::resource('payments', 'PaymentController', [
        'only' => ['index', 'create', 'destroy', 'store']
    ]);

	Route::get('dashboard', 'HomeController@index')->name('dashboard');

    Route::resource('stock-adjustments', 'StockAdjustmentController', [
        'only' => ['index', 'create', 'store']
    ]);

    Route::resource('users', 'UserController');

    Route::get('profile', 'ProfileController@index')->name('profile.show');
    Route::post('profile', 'ProfileController@store')->name('profile.update');

    Route::redirect('/', '/dashboard', 301);

    Route::resource('roles', 'RoleController', [
        'except' => ['show']
    ]);
});

app/Models/Order.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use Eloquent as Model;
use Iatstuti\Database\Support\CascadeSoftDeletes;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Order
 * @package App\Models
 * @version September 8, 2017, 8:16 am UTC
 *
 * @property integer customer_id
 * @property timestamp ordered_at
 * @property decimal total_amount
 * @property decimal paid_amount
 */
class Order extends Model
{
    use SoftDeletes, CascadeSoftDeletes, Sluggable;

    public $table = 'orders';
    

    protected $dates = ['deleted_at', 'ordered_at'];

    protected $cascadeDeletes = ['payments'];

    public $fillable = [
        'customer_id',
        'ordered_at',
        'total_amount',
        'mode',
    ];

    protected $appends = ['due_amount'];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'customer_id' => 'integer',
        'total_amount' => 'float',
        'paid_amount' => 'float',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'customer' => 'required|exists:customers,id',
        'ordered_at' => 'date|required',
        'total_amount' => 'required|numeric|min:0',
        'paid_amount' => 'numeric|nullable',
        'products' => 'required|array'
    ];

    public function sluggable()
    {
        return [
            'uid' => [
                'source' => 'id',
                'unique' => true,
                'separator' => '-',
                'onUpdate' => true,
                'method' => function ($string, $separator) {
                    return 'OR' . $separator . str_pad($string, 5, '0', STR_PAD_LEFT);
                }
            ],
        ];
    }

    public function products()
    {
        return $this->belongsToMany(Product::class, 'order_products')
            ->withPivot(['quantity', 'price', 'amount', 'discount', 'vat']);
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function payments()
    {
        return $this->hasMany(Payment::class);
    }
    
    public function getDueAmountAttribute()
    {
        return (float)number_format($this->total_amount - $this->paid_amount, 2 , '.' , '');
    }

    public function setOrderedAtAttribute($value)
    {
        $this->attributes['ordered_at'] = Carbon::parse($value);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\OrderDataTable;
use App\Http\Controllers\AppBaseController;
use App\Http\Requests\CreateOrderRequest;
use App\Http\Requests\UpdateOrderRequest;
use App\Repositories\CustomerRepository;
use App\Repositories\OrderRepository;
use Flash;
use Illuminate\Http\Request;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class OrderController extends AppBaseController
{
    /** @var  OrderRepository */
    private $orderRepository;
    private $customerRepository;

    public function __construct(OrderRepository $orderRepo, CustomerRepository $customerRepo)
    {
        $this->orderRepository = $orderRepo;
        $this->customerRepository = $customerRepo;
    }

    /**
     * Display a listing of the Order.
     *
     * @param Request $request
     * @return Response
     */
    public function index(OrderDataTable $orderDataTable)
    {
        // $this->orderRepository->pushCriteria(new RequestCriteria($request));
        // $orders = $this->orderRepository->all();

        // return view('orders.index')
        //     ->with('orders', $orders);
        
        return $orderDataTable->render('orders.index');
    }

    /**
     * Show the form for creating a new Order.
     *
     * @return Response
     */
    public function create()
    {
        $customers = $this->customerRepository->all();
        return view('orders.create', compact('customers'));
    }

    /**
     * Store a newly created Order in storage.
     *
     * @param CreateOrderRequest $request
     *
     * @return Response
     */
    public function store(CreateOrderRequest $request)
    {
        $input = $request->all();

        $order = $this->orderRepository->create($input);

        Flash::success('Order saved successfully.');

        return redirect(route('orders.index'));
    }

    /**
     * Display the specified Order.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $order = $this->orderRepository->with(['customer', 'payments'])->findByUid($id);

        if (empty($order)) {
            Flash::error('Order not found');

            return redirect(route('orders.index'));
        }

        return view('orders.show')->with('order', $order);
    }

    /**
     * Show the form for editing the specified Order.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $order = $this->orderRepository->with(['products.category'])->findByUid($id);

        if (empty($order)) {
            Flash::error('Order not found');

            return redirect(route('orders.index'));
        }

        $customers = $this->customerRepository->all();

        return view('orders.edit', compact('customers', 'order'));
    }

    /**
     * Update the specified Order in storage.
     *
     * @param  int              $id
     * @param UpdateOrderRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOrderRequest $request)
    {
        $order = $this->orderRepository->findByUid($id);

        if (empty($order)) {
            Flash::error('Order not found');

            return redirect(route('orders.index'));
        }

        $order = $this->orderRepository->update($request->all(), $id);

        Flash::success('Order updated successfully.');

        return redirect(route('orders.index'));
    }

    /**
     * Remove the specified Order from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $order = $this->orderRepository->findByUid($id);

        if (empty($order)) {
            Flash::error('Order not found');

            return redirect(route('orders.index'));
        }

        $this->orderRepository->deleteByUid($id);

        Flash::success('Order deleted successfully.');

        return redirect(route('orders.index'));
    }
}

resources/views/orders/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Order
        </h1>
    </section>
    <div class="content">
        @include('flash::message')
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    @yield('form.open')
                    {!! Form::open(['route' => 'orders.store']) !!}

                        @include('orders.fields')

                    {!! Form::close() !!}
                    @yield('form.close')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/orders/datatables_actions.blade.php
{!! Form::open(['route' => ['orders.destroy', $uid], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('orders.show', $uid) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    {{-- <a href="{{ route('orders.edit', $uid) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!} --}}
</div>
{!! Form::close() !!}

resources/views/orders/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Order
        </h1>
   </section>
   <div class="content">
       @include('flash::message')
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                    @yield('form.open')
                    {!! Form::model($order, ['route' => ['orders.update', $order->uid], 'method' => 'patch']) !!}

                        @include('orders.fields')

                    {!! Form::close() !!}
                    @yield('form.close')
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Orders</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('orders.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('orders.table')
            </div>
        </div>
    </div>
@endsection

resources/views/orders/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header hidden-print">
        <h1>
            Order
        </h1>
    </section>
    <div class="content hidden-print">
        <div class="row">
            <div class="col-sm-9">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="btn-group pull-right btn-group-sm" role="group">
                            {{-- <a href="#" class="btn btn-primary">
                                <i class="fa fa-envelope"></i>
                                Email
                            </a> --}}
                            <a href="javascript:window.print()" class="btn btn-primary">
                                <i class="fa fa-print"></i>
                                Print</a>
                            <a href="{{ route('orders.edit', $order->uid) }}" class="btn btn-primary">
                                <i class="fa fa-pencil"></i>
                                Edit</a>
                        </div>
                        <div class="clearfix"></div>
                        <div class="row">
                            <div class="form-group col-sm-6">
                                <label>Date</label>
                                <p>{{ $order->created_at->format("M d, Y H:i A") }}</p>
                            </div>
                            <div class="form-group col-sm-6">
                                <label>Status</label>
                                <p>{{ $order->created_at->format("M d, Y H:i A") }}</p>
                            </div>
                            <div class="form-group col-sm-6">
                                <label>Total Amount</label>
                                <p>{{ $order->total_amount }}</p>
                            </div>
                            <div class="form-group col-sm-6">
                                <label>Paid Amount</label>
                                <p>{{ $order->paid_amount }}</p>
                            </div>
                            <div class="form-group col-sm-6">
                                <label>Due Amount</label>
                                <p>{{ $order->due_amount }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <h4>Order Items</h4>
                <div class="box box-primary">
                    <table class="table table table-hover">
                        <thead>
                            <tr>
                                <td>Product</td>
                                <td>Category</td>
                                <td>Price</td>
                                <td>Quantity</td>
                                <td>Amount</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($order->products as $item)
                                <tr>
                                    <td>{{ $item->name }}</td>
                                    <td>{{ optional($item->category)->name }}</td>
                                    <td>{{ ((float) $item->pivot->amount - (float) $item->pivot->discount + (float) $item->pivot->vat) / $item->pivot->quantity }}</td>
                                    <td>{{ $item->pivot->quantity }}</td>
                                    <td>{{ $item->pivot->amount }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">
                            Customer
                        </h3>
                    </div>
                    <div class="box-body">
                        <dl class="">
                            <dt>Name</dt>
                            <dd><a href="{{ route('customers.show', $order->customer->uid) }}">{{ $order->customer->name }}</a></dd>
                            <dt>Email</dt>
                            <dd><a href="mailto:{{ $order->customer->email }}">{{ $order->customer->email }}</a></dd>
                            <dt>Phone</dt>
                            <dd>{{ $order->customer->phone }}</dd>
                        </dl>
                    </div>
                </div>
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">
                            Payments
                        </h3>
                    </div>
                    <table class="table-hover table">
                        {{-- <thead>
                            <tr>
                                <td>Date</td>
                                <td>Amount</td>
                            </tr>
                        </thead> --}}
                        <tbody>
                            @forelse($order->payments as $payment)
                                <tr>
                                    <td>{{ $payment->paid_at->format("M d, Y H:i A") }}</td>
                                    <td>{{ $payment->amount }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="2">No Payments</td>
                                </tr>
                            @endforelse
                        </tbody>
                        @if($order->paid_amount > 0)
                            <tfoot>
                                <tr>
                                    <td colspan="2">
                                        <p><strong>Total Paid Amount:</strong> P {{ $order->paid_amount }}</p>
                                    </td>
                                </tr>
                            </tfoot>
                        @endif
                    </table>
                </div>
            </div>
        </div>
        <a href="{!! route('orders.index') !!}" class="btn btn-default">
            <i class="fa fa-angle-double-left"></i>
            Back</a>
    </div>
    <div class="section visible-print-block invoice">
        <h2 class="page-header">
            {{ config("app.name") }}
            
            <small class="pull-right">
                {{ $order->created_at->format("M d, Y H:i A") }}
            </small>
        </h2>
        <div class="row">
            <div class="col-xs-4">
                From
                <address>
                    <strong>{{ config("app.name") }}</strong><br>
                    2nd Fl. Gillamac's Bldg., CPG Ave. <br>
                    Tagbilaran City, Bohol <br>
                    Phone: +63917-505-9268 <br>
                    Tel. No. (038) 501-9354 <br>
                    E-mail: roy@yorbs.net <br>
                </address>
            </div>
            <div class="col-xs-4">
                To
                <address>
                    <strong>{{ $order->customer->name }}</strong><br>
                    @if ($order->customer->phone)
                        Phone: {{ $order->customer->phone }} <br>
                    @endif
                    @if ($order->customer->email)
                        Email: {{ $order->customer->email }} <br>
                    @endif
                </address>
            </div>
            <div class="col-xs-4">
                <b>Order: #{{ $order->id }}</b><br><br>
                <b>Order ID:</b> {{ $order->uid }} <br>
                <b>Account:</b> {{ $order->customer->uid }} <br>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Qty</th>
                            <th>Product</th>
                            <th>Code</th>
                            <th>Description</th>
                            <th>Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($order->products as $product)
                            <tr>
                                <td>{{ $product->pivot->quantity }}</td>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->code }}</td>
                                <td>{{ $product->description }}</td>
                                <td>{{ $product->pivot->amount }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6">
            </div>
            <div class="col-xs-6">
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Tax:</th>
                            <td>{{ $order->products->sum('pivot.tax') }}</td>
                        </tr>
                        <tr>
                            <th>Discount:</th>
                            <td>{{ $order->products->sum('pivot.discount') }}</td>
                        </tr>
                        <tr>
                            <th>Total:</th>
                            <td>{{ $order->total_amount }}</td>
                        </tr>
                        <tr>
                            <th>Paid:</th>
                            <td>{{ $order->paid_amount }}</td>
                        </tr>
                        <tr>
                            <th>Due:</th>
                            <td>{{ $order->due_amount }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/orders/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $order->id !!}</p>
</div>

<!-- Customer Id Field -->
<div class="form-group">
    {!! Form::label('customer_id', 'Customer Id:') !!}
    <p>{!! $order->customer_id !!}</p>
</div>

<!-- Ordered At Field -->
<div class="form-group">
    {!! Form::label('ordered_at', 'Ordered At:') !!}
    <p>{!! $order->ordered_at !!}</p>
</div>

<!-- Total Amount Field -->
<div class="form-group">
    {!! Form::label('total_amount', 'Total Amount:') !!}
    <p>{!! $order->total_amount !!}</p>
</div>

<!-- Paid Amount Field -->
<div class="form-group">
    {!! Form::label('paid_amount', 'Paid Amount:') !!}
    <p>{!! $order->paid_amount !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $order->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $order->updated_at !!}</p>
</div>

resources/views/orders/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection